import { CountryInfo } from "../types/country-info";

export const countryInfo: CountryInfo[] = [
  { countryCode: '93', name: 'Afeganistão' },
  { countryCode: '355', name: 'Albânia' },
  { countryCode: '213', name: 'Algéria' },
  { countryCode: '1684', name: 'Samoa Americana' },
  { countryCode: '376', name: 'Andorra' },
  { countryCode: '244', name: 'Angola' },
  { countryCode: '1264', name: 'Anguilla' },
  { countryCode: '672', name: 'Antártida' },
  { countryCode: '1268', name: 'Antigua e Barbuda' },
  { countryCode: '54', name: 'Argentina' },
  { countryCode: '374', name: 'Armênia' },
  { countryCode: '297', name: 'Aruba' },
  { countryCode: '61', name: 'Austrália' },
  { countryCode: '43', name: 'Áustria' },
  { countryCode: '994', name: 'Azerbaijão' },
  { countryCode: '1242', name: 'Bahamas' },
  { countryCode: '973', name: 'Bahrein' },
  { countryCode: '880', name: 'Bangladesh' },
  { countryCode: '246', name: 'Barbados' },
  { countryCode: '375', name: 'Bielorrússia' },
  { countryCode: '32', name: 'Bélgica' },
  { countryCode: '501', name: 'Belize' },
  { countryCode: '229', name: 'Benin' },
  { countryCode: '1441', name: 'Bermuda' },
  { countryCode: '975', name: 'Butão' },
  { countryCode: '591', name: 'Bolívia' },
  { countryCode: '387', name: 'Bósnia e Herzegovina' },
  { countryCode: '267', name: 'Botswana' },
  { countryCode: '47', name: 'Ilha Bouvet' },
  { countryCode: '55', name: 'Brasil' },
  { countryCode: '246', name: 'Território Britânico do Oceano Índico' },
  { countryCode: '673', name: 'Brunei' },
  { countryCode: '359', name: 'Bulgária' },
  { countryCode: '226', name: 'Burkina Faso' },
  { countryCode: '257', name: 'Burundi' },
  { countryCode: '855', name: 'Camboja' },
  { countryCode: '237', name: 'Camarões' },
  { countryCode: '1', name: 'Canadá' },
  { countryCode: '238', name: 'Cabo Verde' },
  { countryCode: '1345', name: 'Ilhas Cayman' },
  { countryCode: '236', name: 'República Centro-Africana' },
  { countryCode: '235', name: 'Chade' },
  { countryCode: '56', name: 'Chile' },
  { countryCode: '86', name: 'China' },
  { countryCode: '61', name: 'Ilha Christmas' },
  { countryCode: '672', name: 'Ilhas Cocos (Keeling)' },
  { countryCode: '57', name: 'Colômbia' },
  { countryCode: '269', name: 'Comores' },
  { countryCode: '242', name: 'Congo' },
  { countryCode: '242', name: 'Congo (DR)' },
  { countryCode: '682', name: 'Ilhas Cook' },
  { countryCode: '506', name: 'Costa Rica' },
  { countryCode: '225', name: 'Costa do Marfim' },
  { countryCode: '385', name: 'Croácia' },
  { countryCode: '53', name: 'Cuba' },
  { countryCode: '357', name: 'Chipre' },
  { countryCode: '420', name: 'República Tcheca' },
  { countryCode: '45', name: 'Dinamarca' },
  { countryCode: '253', name: 'Djibuti' },
  { countryCode: '1767', name: 'Dominica' },
  { countryCode: '1809', name: 'República Dominicana' },
  { countryCode: '593', name: 'Equador' },
  { countryCode: '20', name: 'Egito' },
  { countryCode: '503', name: 'El Salvador' },
  { countryCode: '240', name: 'Guiné Equatorial' },
  { countryCode: '291', name: 'Eritreia' },
  { countryCode: '372', name: 'Estônia' },
  { countryCode: '251', name: 'Etiópia' },
  { countryCode: '500', name: 'Ilhas Malvinas' },
  { countryCode: '298', name: 'Ilhas Faroe' },
  { countryCode: '679', name: 'Fiji' },
  { countryCode: '358', name: 'Finlândia' },
  { countryCode: '33', name: 'França' },
  { countryCode: '594', name: 'Guiana Francesa' },
  { countryCode: '689', name: 'Polinésia Francesa' },
  { countryCode: '33', name: 'Terras Austrais e Antárticas Francesas' },
  { countryCode: '241', name: 'Gabão' },
  { countryCode: '220', name: 'Gâmbia' },
  { countryCode: '995', name: 'Geórgia' },
  { countryCode: '49', name: 'Alemanha' },
  { countryCode: '233', name: 'Gana' },
  { countryCode: '350', name: 'Gibraltar' },
  { countryCode: '30', name: 'Grécia' },
  { countryCode: '299', name: 'Groelândia' },
  { countryCode: '1473', name: 'Granada' },
  { countryCode: '590', name: 'Guadalupe' },
  { countryCode: '1671', name: 'Guão' },
  { countryCode: '502', name: 'Guatemala' },
  { countryCode: '224', name: 'Guiné' },
  { countryCode: '245', name: 'Guiné-Bissau' },
  { countryCode: '592', name: 'Guiana' },
  { countryCode: '509', name: 'Haiti' },
  { countryCode: '672', name: 'Ilhas Heard e McDonald' },
  { countryCode: '39', name: 'Vaticano' },
  { countryCode: '504', name: 'Honduras' },
  { countryCode: '852', name: 'Hong Kong' },
  { countryCode: '36', name: 'Hungria' },
  { countryCode: '354', name: 'Islândia' },
  { countryCode: '91', name: 'Índia' },
  { countryCode: '62', name: 'Indonésia' },
  { countryCode: '98', name: 'Iran' },
  { countryCode: '964', name: 'Iraque' },
  { countryCode: '353', name: 'Irlanda' },
  { countryCode: '972', name: 'Israel' },
  { countryCode: '39', name: 'Itália' },
  { countryCode: '1876', name: 'Jamaica' },
  { countryCode: '81', name: 'Japão' },
  { countryCode: '962', name: 'Jordânia' },
  { countryCode: '7', name: 'Cazaquistão' },
  { countryCode: '254', name: 'Quênia' },
  { countryCode: '686', name: 'Kiribati' },
  { countryCode: '850', name: 'Coreia do Norte' },
  { countryCode: '82', name: 'Coreia do Sul' },
  { countryCode: '965', name: 'Kuwait' },
  { countryCode: '996', name: 'Quirguistão' },
  { countryCode: '856', name: 'Laos' },
  { countryCode: '371', name: 'Letônia' },
  { countryCode: '961', name: 'Líbano' },
  { countryCode: '266', name: 'Lesoto' },
  { countryCode: '231', name: 'Libéria' },
  { countryCode: '218', name: 'Líbia' },
  { countryCode: '423', name: 'Liechtenstein' },
  { countryCode: '370', name: 'Lituânia' },
  { countryCode: '352', name: 'Luxemburgo' },
  { countryCode: '853', name: 'Macao' },
  { countryCode: '389', name: 'Macedônia' },
  { countryCode: '261', name: 'Madagascar' },
  { countryCode: '265', name: 'Malawi' },
  { countryCode: '60', name: 'Malásia' },
  { countryCode: '960', name: 'Maldivas' },
  { countryCode: '223', name: 'Mali' },
  { countryCode: '356', name: 'Malta' },
  { countryCode: '692', name: 'Ilhas Marshall' },
  { countryCode: '596', name: 'Martinica' },
  { countryCode: '222', name: 'Mauritânia' },
  { countryCode: '230', name: 'Maurício' },
  { countryCode: '269', name: 'Mayotte' },
  { countryCode: '52', name: 'México' },
  { countryCode: '691', name: 'Micronésia' },
  { countryCode: '373', name: 'Moldova' },
  { countryCode: '377', name: 'Mônaco' },
  { countryCode: '976', name: 'Mongólia' },
  { countryCode: '1664', name: 'Montserrat' },
  { countryCode: '212', name: 'Marrocos' },
  { countryCode: '258', name: 'Moçambique' },
  { countryCode: '95', name: 'Birmânia' },
  { countryCode: '264', name: 'Namíbia' },
  { countryCode: '674', name: 'Nauru' },
  { countryCode: '977', name: 'Nepal' },
  { countryCode: '31', name: 'Holanda' },
  { countryCode: '599', name: 'Antilhas Holandesas' },
  { countryCode: '687', name: 'Nova Caledônia' },
  { countryCode: '64', name: 'Nova Zelândia' },
  { countryCode: '505', name: 'Nicarágua' },
  { countryCode: '227', name: 'Niger' },
  { countryCode: '234', name: 'Nigéria' },
  { countryCode: '683', name: 'Niue' },
  { countryCode: '672', name: 'Ilha Norfolk' },
  { countryCode: '1670', name: 'Ilhas Marianas do Norte' },
  { countryCode: '47', name: 'Noruega' },
  { countryCode: '968', name: 'Omã' },
  { countryCode: '92', name: 'Paquistão' },
  { countryCode: '680', name: 'Palau' },
  { countryCode: '970', name: 'Palestina' },
  { countryCode: '507', name: 'Panamá' },
  { countryCode: '675', name: 'Papua-Nova Guiné' },
  { countryCode: '595', name: 'Paraguai' },
  { countryCode: '51', name: 'Peru' },
  { countryCode: '63', name: 'Filipinas' },
  { countryCode: '672', name: 'Ilhas Picárnia' },
  { countryCode: '48', name: 'Polônia' },
  { countryCode: '351', name: 'Portugal' },
  { countryCode: '1787', name: 'Porto Rico' },
  { countryCode: '974', name: 'Catar' },
  { countryCode: '262', name: 'Reunião' },
  { countryCode: '40', name: 'Romênia' },
  { countryCode: '70', name: 'Rússia' },
  { countryCode: '250', name: 'Ruanda' },
  { countryCode: '290', name: 'Santa Helena' },
  { countryCode: '1869', name: 'São Cristóvão' },
  { countryCode: '1758', name: 'Santa Lúcia' },
  { countryCode: '508', name: 'São Pedro e Miquelon' },
  { countryCode: '1784', name: 'São Vicente e Granadinas' },
  { countryCode: '684', name: 'Samoa' },
  { countryCode: '378', name: 'São Marino' },
  { countryCode: '239', name: 'Sao Tomé e Príncipe' },
  { countryCode: '966', name: 'Arábia Saudita' },
  { countryCode: '221', name: 'Senegal' },
  { countryCode: '381', name: 'Sérvia e Montenegro' },
  { countryCode: '248', name: 'Seicheles' },
  { countryCode: '232', name: 'República da Serra Leoa' },
  { countryCode: '65', name: 'Singapura' },
  { countryCode: '421', name: 'Eslováquia' },
  { countryCode: '386', name: 'Eslovênia' },
  { countryCode: '677', name: 'Ilhas Salomão' },
  { countryCode: '252', name: 'Somália' },
  { countryCode: '27', name: 'África do Sul' },
  { countryCode: '500', name: 'Ilhas Geórgia do Sul e Sandwich do Sul' },
  { countryCode: '34', name: 'Espanha' },
  { countryCode: '94', name: 'Sri Lanka' },
  { countryCode: '249', name: 'Sudão' },
  { countryCode: '597', name: 'Suriname' },
  { countryCode: '47', name: 'Esvalbarde' },
  { countryCode: '268', name: 'Suazilândia' },
  { countryCode: '46', name: 'Suécia' },
  { countryCode: '41', name: 'Suiça' },
  { countryCode: '963', name: 'Síria' },
  { countryCode: '886', name: 'Taiwan' },
  { countryCode: '992', name: 'Tajiquistão' },
  { countryCode: '255', name: 'Tanzânia' },
  { countryCode: '66', name: 'Tailândia' },
  { countryCode: '670', name: 'Timor-Leste' },
  { countryCode: '228', name: 'Togo' },
  { countryCode: '690', name: 'Toquelau' },
  { countryCode: '676', name: 'Tonga' },
  { countryCode: '1868', name: 'Trinidad e Tobago' },
  { countryCode: '216', name: 'Tunísia' },
  { countryCode: '90', name: 'Turquia' },
  { countryCode: '7370', name: 'Turcomenistão' },
  { countryCode: '1649', name: 'Ilhas Turks e Caicos' },
  { countryCode: '688', name: 'Tuvalu' },
  { countryCode: '256', name: 'Uganda' },
  { countryCode: '380', name: 'Ucrânia' },
  { countryCode: '971', name: 'Emirados Árabes' },
  { countryCode: '44', name: 'Reino Unido' },
  { countryCode: '1', name: 'Estados Unidos' },
  { countryCode: '1', name: 'Ilhas Menores Distantes dos Estados Unidos' },
  { countryCode: '598', name: 'Uruguai' },
  { countryCode: '998', name: 'Uzbequistão' },
  { countryCode: '678', name: 'Vanuatu' },
  { countryCode: '58', name: 'Venezuela' },
  { countryCode: '84', name: 'Vietnam' },
  { countryCode: '1284', name: 'Ilhas Virgens Inglesas' },
  { countryCode: '1340', name: 'Ilhas Virgens (USA)' },
  { countryCode: '681', name: 'Wallis e Futuna' },
  { countryCode: '212', name: 'Saara Ocidental' },
  { countryCode: '967', name: 'Iêmen' },
  { countryCode: '260', name: 'Zâmbia' },
  { countryCode: '263', name: 'Zimbábue' },
];
